@Api_HostAddress = https://localhost:7052

### Register
# @name register
POST {{Api_HostAddress}}/identity/register
Content-Type: application/json
Accept: application/json

{
  "email": "hugo@acheve.es",
  "password": "Patata.!123"
}


### Login
# @name login
POST {{Api_HostAddress}}/identity/login
Content-Type: application/json
Accept: application/json

{
  "email": "hugo@acheve.es",
  "password": "Patata.!321"
}


### Get Weather Forecast
# @name get-weather-forecast

@access_token={{login.response.body.accessToken}}
@refresh_token={{login.response.body.refreshToken}}

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{access_token}}

### Manage info
GET {{Api_HostAddress}}/identity/manage/info
Accept: application/json
Authorization: Bearer {{access_token}}

### Confirm email
POST {{Api_HostAddress}}/identity/resendConfirmationEmail
Content-Type: application/json
Accept: application/json

{
  "email": "hugo@acheve.es"
}

### Forgot password
POST {{Api_HostAddress}}/identity/forgotPassword
Content-Type: application/json
Accept: application/json

{
  "email": "hugo@acheve.es"
}

### Reset password
POST {{Api_HostAddress}}/identity/resetPassword
Content-Type: application/json
Accept: application/json

{
  "email": "hugo@acheve.es",
  "resetCode": "Q2ZESjhHMGNhVkpDTEVCTW50VWpsOFVyRmRMeVpBZXhmSXB6QnRON2Q5Tk4rd2NZSEp2NEZQaUZpc0I5bUVxU0VEVndLOFlicERaVkhKN0h4VzBqMmVpQllGWXpOV2QyZ1pOd25hQ01WTkw4ODgzTWdCbzUyVHYzNGRseFhtcWFPY1B0UTM5TTAzV3FTUlJzWGkyWWdSOFVQUWlzRTBzTWF5OHkyZHZwYkNUK0pYck81aHFFME1Nc2VBZnFCdmg0aUVIV1k3d1ZKei96b1VQMDZHS3gyb1Q4OTRBRW5McGhGS216bE16S1V2QTFCampZ",
  "newPassword": "Patata.!321"
}